Section "InputClass"
  Identifier        "Penmount Touch Screen"
  MatchProduct      "PenMount"
  MatchIsKeyboard   "off"
  MatchDevicePath   "/dev/input/event*"  
  Driver            "penmount"  
  Option            "SoundPath"        ""
  Option            "DebugLevel"       "1"
EndSection

Section "InputClass"
  Identifier         "Penmount Touch Screen"
  MatchProduct       "PENMOUNT"
  MatchIsTouchScreen "on"  
  MatchDevicePath    "/dev/input/event*"
  Driver             "penmount"  
  Option             "SoundPath"        ""
  Option             "DebugLevel"       "1"  
EndSection

Section "InputClass"
  Identifier         "Penmount Touch Screen"
  MatchProduct       "ImageBroad"
  MatchDevicePath    "/dev/input/event*"
  Driver             "penmount"
  Option             "SoundPath"        ""
  Option             "DebugLevel"       "1"
  
EndSection


