########  /etc/X11/xorg.conf  ########

##############################################################################
# Detect Device
#   COM : /dev/ttyS0, /dev/ttyS1...
#   USB : /dev/input/event3, /dev/input/event3...
##############################################################################
DetectUSB=1
#DetectCOM=1
Device=/dev/input/event5
GrabDevice=0

##############################################################################
# Protocol : PM9000, PM5000, PM6000USB, PM6000COM, PMLPC
##############################################################################
Protocol=PM6000USB

##############################################################################
# UART / RS-232 Settings
# Baud Rate for PM9000 and PM6000COM : 19200 or 9600
##############################################################################
BaudRate=19200
EnableTX=1

##############################################################################
# PenMount configuration file
##############################################################################
# ConfigFile=/etc/penmount/penmount.dat
DefaultData=0

##############################################################################
# Option AlwaysCore in Section ServerLayout
# Ubuntu 8.04 should NOT be AlwaysCore
##############################################################################
AlwaysCore=2

##############################################################################
# X window Screen Number (default = 0)
##############################################################################
ScreenNumber=0

##############################################################################
# PenMount A/D bit : 10-bit or 12-bit
##############################################################################
ADBit=10

##############################################################################
# XRandR : 1=XRandR enable, 0=disable
##############################################################################
RandR=1

##############################################################################
# Debug for PenMount X input driver
##############################################################################
DebugLevel=2
#DebugFile=/etc/penmount/penmount.log

########  /etc/penmount.dat  ########

##############################################################################
# Send (left/middle/right) button when press and hold/
#  e.g. : RightButton / MiddleButton / LeftButton
#  P.S. : RightButton  : button 3
#         MiddleButton : button 2
#         LeftButton   : button 1
##############################################################################
PressAndHoldButton=RightButton
#PressAndHoldButton=MiddleButton
#PressAndHoldButton=LeftButton


##############################################################################
#   Click Mode           Pen Down       Pen Hold    Pen Move     Pen Up
#---------------------------------------------------------------------------
#   Mouse             :  LEFT-DOWN      --------    --------     LEFT-UP
#   Touch             :  
#   Hover             :  ---------      --------    --------     LEFT-DOWN-UP
#   Button            :  LEFT-DOWN-UP   --------    --------     -------
##############################################################################
#TouchMode=Touch
#TouchMode=Button
#TouchMode=Hover
TouchMode=Mouse

##############################################################################
#  Press and hold function switch (1=on, 0=off)
##############################################################################
HoldSwitch=0

##############################################################################
#  Hold time for Press and Hold (unit : mini seconds)
##############################################################################
HoldTime=2000

##############################################################################
#  Hold Area is for press and hold, calculate the distance of
#   current X,Y and pen-down X,Y
#   if distance >  HoldArea : PRESS AND HOLD IS DISABLE
#      distance <= HoldArea : PRESS AND HOLD IS ENABLE (when over hold time)
##############################################################################
HoldArea=32

##############################################################################
#  Scale to screen resolution
#    1=enable  (screen resolution) e.g. 1024x768 --> 0~1023 and 0~767
#    0=disable (panel resolution)  e.g. 0~1023 and 0~1023
##############################################################################
ScreenScale=0

##############################################################################
#  Fuzz Point
#   0 : disable
#   1 : Linux input fuzz
#   2 : four-points average
#   3 : eight-points average
#  FuzzValue is used for Linux input fuzz
##############################################################################
FuzzPoint=0
FuzzValue=2

##############################################################################
#  Rotation
#  0 : normal
#  1 : left (90-deg)
#  2 : inverted (180-deg)
#  3 : right (90-deg)
##############################################################################
Rotation=0

##############################################################################
#  Edge Compensations for calibration
##############################################################################
XMinOffset=10
XMaxOffset=10
YMinOffset=10
YMaxOffset=10

##############################################################################
#  Beep Configuration
##############################################################################
#    BeepType = 0 : Slience
#             = 1 : Beep when pen down
#             = 2 : Beep when pen up
#             = 3 : Beep when pen down and pen up
#
#    BeepFreqDn / BeepFreqUp
#       Beep Frequency for pen down and pen up
#
#    BeepDelayDn / BeepDelayUp
#       Beep delay time for pen down and pen up
#       (unit : mini seconds)
##############################################################################
BeepType=0
BeepFreqDn=880
BeepDelayDn=100
BeepFreqUp=1200
BeepDelayUp=100
BeepOutput=audio
SoundPath=/etc/penmount/beep.wav

##############################################################################
#  Calibration Configuration
##############################################################################
#            = 4  : 4-points calibration
#            = 9  : 9-points calibration
#            = 16 : 16-points calibration
#            = 25 : 25-points calibration
#
#  CalibType=4,  CalData=X0,Y0,X1,Y1,X2,Y2,X3,Y3
#  CalibType=9,  CalData=X0,Y0,X1,Y1........,X7,Y7,X8,Y8
#  CalibType=16, CalData=X0,Y0,X1,Y1........,X14,Y14,X15,Y15
#  CalibType=25, CalData=X0,Y0,X1,Y1........,X23,Y23,X24,Y24
##############################################################################
#CalibType=4
#CalibData=1023,1023,0,1023,0,0,1023,0


##############################################################################
#  Mapped Monitor Settings
##############################################################################
Monitor=default

##############################################################################
#  Jitter Filter
##############################################################################
JitterFilter=8

##############################################################################
#  Double Click
##############################################################################
DoubleClickSuppressRange=0
DoubleClickSuppressTime=800

##############################################################################
#  Use Calibration Data in EEPROM (PM6000)
#  0: Do not use EEPROM, use port specific calibration file.
#  1: Use EEPROM, use port specific calibration file.
#  2: Do not use EEPROM, do not use port specific calibration file.
#  3: Use EEPROM, do not use port specific calibration file.
##############################################################################
UseEEPROM=1

##############################################################################
# Customized Feature Index
##############################################################################
ODM_ID=0
